### ISSUE TITLE
./readTable.h:17:10: fatal error: 'bits/stdc++.h' file not found

### ISSUE THREAD

**Issue by andyto1234** [xastprl/chspec#2]
I am having the error: "./readTable.h:17:10: fatal error: 'bits/stdc++.h' file not found" after I typed ./install.sh inside the chapel directory. Wondering if anyone experienced the same error before and how could I solve it?

More details are attached in the screenshot below. Thanks a lot!
<img width="665" alt="Screenshot 2023-09-11 at 23 58 58" src="https://github.com/xastprl/chspec/assets/55692630/088f7585-a422-42d3-8719-5dba17c08497">

**Comment by biswajitmb** [comment]
Hi, This error indicates that the "stdc++.h" (https://gcc.gnu.org/onlinedocs/gcc-4.8.0/libstdc++/api/a01541_source.html) header file of GNU C++ library is missing in your system library path. This is a precompiled header file.

However, I think this is no longer needed for chspec. Thus you can delete the line "#include <bits/stdc++.h>" from "readTable.h" and reinstall the package by running "./install.sh". It should resolve this problem. 

-- Biswajit

**Comment by andyto1234** [comment]
Hi Biswajit, thank you so much! This indeed solves the problem
